'use strict';
(()=>{
const CAL='yos-taxi-calendar-v1';
const readCalendar=()=>{try{return JSON.parse(localStorage.getItem(CAL)||'{}')}catch{return{}}};
const calendarDay=()=>readCalendar().days?.[state.businessDate]||{status:'unknown',target:0,weather:'未確認',factor:1,event:''};
function getStrategy(){const c=calendarDay(),d=new Date(`${state.businessDate}T12:00:00`),w=d.getDay(),busy=w===5||w===6,rain=['雨','強雨','台風'].includes(c.weather),event=String(c.event||'').trim();let headline=busy?'那覇へ早めに寄せ、夜需要を取り切る':'宜野湾・浦添で反応を確認し、那覇へ寄せる',reason=`目標 ${money(settings.targetSales||c.target||0)}。空車15分でエリア変更し、空車走行を最短にする。`,early=busy?'配車反応を見ながら那覇へ。18時台から久茂地方面を意識':'宜野湾・浦添で配車反応を確認。弱ければ那覇へ移動',peak='久茂地・松山・若狭。GO・付け待ちを優先し、流し過ぎない',late='松山・若狭・ホテル周辺。1〜3時は待機場所を絞る';if(rain){headline='雨需要を拾う。屋根のある乗降地点を優先';reason='ホテル・商業施設・繁華街の出口を狙い、濡れる場所で長時間待たない。'}if(event){headline='確認済みイベント需要を軸に組み立てる';reason=`${event}。終了時刻の前後は会場直近を避け、外周で乗車しやすい場所を選ぶ。`}if(c.status==='off'){headline='公休。営業せず回復を優先';reason='確認済みの公休日です。休養と次回営業の準備を優先する。'}if(state.status!=='before'&&state.status!=='ended')reason+=' 営業中は下のIMada判断を優先。';return{headline,reason,early,peak,late,weather:c.weather||'未確認',event:event||'未確認'}}
function setup(){const top=document.querySelector('.top');if(top&&!top.querySelector('.brand-mark-v9')){top.insertAdjacentHTML('afterbegin','<div class="brand-mark-v9">Y</div>');top.querySelector('.eyebrow').textContent='YOS TAXI';top.querySelector('h1').textContent='営業コントロール'}const status=document.querySelector('.status');if(status&&!document.getElementById('progressFillV9'))status.insertAdjacentHTML('beforeend','<div class="progress-v9"><div class="progress-copy-v9"><span>今日の目標進捗</span><strong id="progressTextV9">¥0 / ¥0</strong></div><div class="progress-track-v9"><i id="progressFillV9"></i></div></div>');const actions=document.querySelector('.actions');if(actions&&!document.querySelector('.actions-v9')){const wrap=document.createElement('section');wrap.className='actions-v9';const primary=document.createElement('div');primary.className='primary-actions-v9';const secondary=document.createElement('div');secondary.className='secondary-actions-v9';['shiftButton','rideButton','dropoffButton','breakButton'].forEach(id=>primary.appendChild(document.getElementById(id)));['memoButton','shareButton','settingsButton','endButton'].forEach(id=>secondary.appendChild(document.getElementById(id)));wrap.append(primary,secondary);actions.replaceWith(wrap)}const imada=document.querySelector('.imada');if(imada){imada.querySelector('h3').textContent='営業中の判断';imada.querySelector('.imada-tag').textContent='IMada × 実営業データ'}if(imada&&!document.getElementById('strategyV9'))imada.insertAdjacentHTML('beforebegin','<section id="strategyV9" class="section-card-v9 strategy-v9" aria-live="polite"><div class="section-head-v9"><h3>今日の営業戦略</h3><span class="section-tag-v9">営業前・全体方針</span></div><div id="strategyHeadlineV9" class="strategy-main-v9">営業前に戦略を確認</div><p id="strategyReasonV9" class="strategy-reason-v9"></p><div class="strategy-timeline-v9"><div class="strategy-row-v9"><span>17:30–22:00</span><b id="strategyEarlyV9"></b></div><div class="strategy-row-v9"><span>22:00–00:30</span><b id="strategyPeakV9"></b></div><div class="strategy-row-v9"><span>00:30–03:00</span><b id="strategyLateV9"></b></div></div><div class="strategy-facts-v9"><span id="strategyWeatherV9" class="fact-v9"></span><span id="strategyEventV9" class="fact-v9"></span><span class="fact-v9">空港待機不可</span><span class="fact-v9">基地入構不可</span></div><button id="strategyButtonV9" class="strategy-button-v9">YOSで今日の戦略を最新化</button></section>');document.getElementById('strategyButtonV9').onclick=handoffStrategy}
function strategyPrompt(){const c=calendarDay();return[`【営業前】今日の営業戦略を最新化して`,`営業日：${state.businessDate}`,`現在地：宜野湾`,`目標：${settings.targetSales||c.target||0}円`,`予定：${settings.plannedStart}〜${settings.plannedEnd}`,`天候：${c.weather||'未確認'}`,`イベント・需要要因：${c.event||'未確認'}`,`制約：基地入構不可・空港待機不可`,`重視：実車率、空車時間、空車走行最小、IMadaメソッド`,`出力：最初のエリア、時間帯別戦略、狙う需要、避ける行動`].join('\n')}
async function handoffStrategy(){const text=strategyPrompt();try{await navigator.clipboard.writeText(text)}catch{prompt('営業前プロンプトをコピーしてください',text);return}const url=String(settings.yosUrl||'').trim();if(url.startsWith('https://chatgpt.com/')){location.href=url;return}alert('営業前プロンプトをコピーしました。設定でYOSチャットURLを登録してください。');openSettings()}
function paint(){setup();const target=Number(settings.targetSales||0),pct=target?Math.min(100,sales()/target*100):0,st=getStrategy();const text=document.getElementById('progressTextV9'),fill=document.getElementById('progressFillV9');if(text)text.textContent=`${money(sales())} / ${money(target)}`;if(fill)fill.style.width=`${pct}%`;const map={strategyHeadlineV9:st.headline,strategyReasonV9:st.reason,strategyEarlyV9:st.early,strategyPeakV9:st.peak,strategyLateV9:st.late,strategyWeatherV9:`天候：${st.weather}`,strategyEventV9:`イベント：${st.event}`};Object.entries(map).forEach(([id,v])=>{const e=document.getElementById(id);if(e)e.textContent=v})}
const oldSummary=summary;summary=function(){const st=getStrategy();return`${oldSummary()}\n今日の営業戦略：${st.headline}`};
setup();paint();setInterval(paint,5000);
})();
