import {SonyRemote,resolveCommands,quickSettingsCandidates,cursorPlan,GoogleTvTextAdapter} from './bravia-core.js';
const $=s=>document.querySelector(s),status=$('#status');let remote,commands={},candidates=[],start;
const secure={async set(value){const p=globalThis.Capacitor?.Plugins?.YOSSecureCredentials;if(!p)throw new Error('KeychainはiOSネイティブ版でのみ利用できます。');await p.set({value});},async get(){const p=globalThis.Capacitor?.Plugins?.YOSSecureCredentials;if(!p)throw new Error('KeychainからPSKを取得できません。');return (await p.get()).value;}};
function report(message,error=false){status.textContent=message;status.dataset.error=String(error);}function refresh(){document.querySelectorAll('[data-command]').forEach(b=>b.disabled=!commands[b.dataset.command]);$('#quick').disabled=!candidates.length;}
async function send(action){try{const command=commands[action];if(!command)throw new Error('このテレビでは未対応です。');await remote.send(command.code);report(`${command.name} を送信しました。`);}catch(error){report(error.message,true);}}
$('#connect').addEventListener('submit',async event=>{event.preventDefault();try{await secure.set($('#psk').value);remote=new SonyRemote($('#host').value,secure);const map=await remote.discover();commands=resolveCommands(map);candidates=quickSettingsCandidates(map);$('#psk').value='';refresh();report(`接続済み · ${map.size}コマンド取得`);}catch(error){report(error.message,true);}});
document.querySelectorAll('[data-command]').forEach(b=>b.addEventListener('click',()=>send(b.dataset.command)));
$('#quick').addEventListener('click',async()=>{const selected=candidates[0];if(!selected)return;try{await remote.send(selected.code);report(`${selected.name} 候補を送信（Quick Settings実機確認は未完了）`);}catch(error){report(error.message,true);}});
const pad=$('#touchpad');pad.addEventListener('pointerdown',e=>{start={x:e.clientX,y:e.clientY,t:performance.now()};pad.setPointerCapture(e.pointerId);});pad.addEventListener('pointerup',async e=>{if(!start)return;const plan=cursorPlan(e.clientX-start.x,e.clientY-start.y,performance.now()-start.t);start=null;if(!plan)return send('confirm');for(let i=0;i<plan.repeats;i++)await send(plan.action);});
$('#keyboard').addEventListener('click',()=>report(new GoogleTvTextAdapter().available?'文字入力を開始します。':'Google TV文字入力: 公開・監査可能な方式がないため未実装です。',true));refresh();
