export const commandAliases = Object.freeze({ power:['PowerOff','Power'], volumeUp:['VolumeUp'], volumeDown:['VolumeDown'], mute:['Mute'], up:['Up'], down:['Down'], left:['Left'], right:['Right'], confirm:['Confirm','Enter'], back:['Return','Back'], home:['Home'], input:['Input'], play:['Play'], pause:['Pause'], channelUp:['ChannelUp'], channelDown:['ChannelDown'] });
export function normalizeHost(value) { const host=value.trim().replace(/^https?:\/\//,'').replace(/:\d+$/,''); if(!host||/[\s/?#]/.test(host)) throw new Error('テレビのホスト名またはIPアドレスを確認してください。'); return host; }
export function parseRemoteControllerInfo(payload) { const list=payload?.result?.[1]; if(!Array.isArray(list)) throw new Error('テレビの対応コマンドを読み取れませんでした。'); return new Map(list.filter(x=>typeof x?.name==='string'&&typeof x?.value==='string').map(x=>[x.name,x.value])); }
export function resolveCommands(map) { return Object.fromEntries(Object.entries(commandAliases).map(([action,names])=>{const name=names.find(n=>map.has(n)); return [action,name?{name,code:map.get(name)}:null];})); }
export function quickSettingsCandidates(map) { return [...map].filter(([name])=>/option|actionmenu|quick|setting/i.test(name)).map(([name,code])=>({name,code})); }
const escapeXml=value=>value.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&apos;'}[c]));
export function irccEnvelope(code) { if(!code) throw new Error('未対応のコマンドです。'); return `<?xml version="1.0"?><s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/" s:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"><s:Body><u:X_SendIRCC xmlns:u="urn:schemas-sony-com:service:IRCC:1"><IRCCCode>${escapeXml(code)}</IRCCCode></u:X_SendIRCC></s:Body></s:Envelope>`; }
export class SonyRemote {
  constructor(host,secretProvider,fetcher=fetch){this.host=normalizeHost(host);this.secretProvider=secretProvider;this.fetcher=fetcher;}
  async headers(extra={}){return {...extra,'X-Auth-PSK':await this.secretProvider.get()};}
  async discover(){const response=await this.fetcher(`http://${this.host}/sony/system`,{method:'POST',headers:await this.headers({'Content-Type':'application/json'}),body:JSON.stringify({method:'getRemoteControllerInfo',params:[],id:1,version:'1.0'})});if(!response.ok)throw new Error(response.status===403?'PSK認証に失敗しました。':'テレビへ接続できません。');return parseRemoteControllerInfo(await response.json());}
  async send(code){const response=await this.fetcher(`http://${this.host}/sony/ircc`,{method:'POST',headers:await this.headers({'Content-Type':'text/xml; charset=UTF-8','SOAPACTION':'"urn:schemas-sony-com:service:IRCC:1#X_SendIRCC"'}),body:irccEnvelope(code)});if(!response.ok)throw new Error(response.status===403?'PSK認証に失敗しました。':'コマンドを送信できませんでした。');}
}
export function cursorPlan(dx,dy,durationMs){const distance=Math.hypot(dx,dy);if(distance<18)return null;const action=Math.abs(dx)>Math.abs(dy)?(dx>0?'right':'left'):(dy>0?'down':'up');const velocity=distance/Math.max(durationMs,1);return {action,repeats:Math.min(8,Math.max(1,Math.floor(distance/45)+Math.floor(velocity/.7)))};}
export class GoogleTvTextAdapter { get available(){return false;} async pair(){throw new Error('公開・監査可能なGoogle TV文字入力方式を採用できていません。');} async sendText(){throw new Error('Google TV文字入力は現在利用できません。');} }
