'use strict';
(()=>{
const KEYS={home:'yos-home-settings-v2',legacy:'yos-home-settings-v1',taxi:'yos-taxi-settings-v2',state:'yos-home-current-state-v1',life:'yos-life-v1',journeys:'hj-domain-journeys-v1',profile:'hj-user-profile-v1',scenes:'hj-daily-scenes-v1',idea:'yos-my-way-ideas-v1',legacyIdea:'yos-idea-memo-v1'};
const $=id=>document.getElementById(id);const clean=(v,n=120)=>typeof v==='string'?v.trim().slice(0,n):'';
const read=(key,fallback)=>{try{return JSON.parse(localStorage.getItem(key)||'null')??fallback}catch{return fallback}};
const write=(key,value)=>{try{localStorage.setItem(key,JSON.stringify(value));return true}catch{return false}};
const dateKey=()=>new Intl.DateTimeFormat('sv-SE',{timeZone:'Asia/Tokyo'}).format(new Date());
const settings=read(KEYS.home,{});const state=read(KEYS.state,{});
const sharedUrl=()=>clean(settings.yosUrl||read(KEYS.legacy,{}).yosUrl||read(KEYS.taxi,{}).yosUrl,500);
const lifeData=()=>read(KEYS.life,null);const todayData=(life=lifeData())=>life?.days?.[life.activeLifeDate||dateKey()]||life?.days?.[dateKey()]||null;
function currentJourney(){const items=read(KEYS.journeys,[]);if(!Array.isArray(items))return null;const focus=clean(read(KEYS.profile,{}).focusDomain,80);return items.find(item=>item?.id===focus)||items[0]||null}
function render(){const life=lifeData();const today=todayData(life);const journey=currentJourney();const scenes=read(KEYS.scenes,[]);const done=Array.isArray(today?.doneToday)?today.doneToday.length:Array.isArray(today?.done)?today.done.length:null;
$('currentSummary').textContent=[{low:'体力は低い',mid:'体力は普通',high:'体力は高い'}[state.energy],clean(state.focus)].filter(Boolean).join('。')||'未設定';
$('destinationSummary').textContent=clean(journey?.theme)||clean(journey?.name)||'未設定';$('progressSummary').textContent=done===null?'データなし':`今日の記録 ${done}件`;$('nextSummary').textContent=clean(today?.nextAction)||clean(today?.priority)||'未設定';
const money=life?.moneySafety || today?.money || {};const income=money.income??money.monthlyIncome,expense=money.expense??money.monthlyExpense,balance=money.currentBalance;const moneyText=value=>Number.isFinite(value)?`${value.toLocaleString('ja-JP')}円`:clean(value,40)||'未設定';$('incomeSummary').textContent=moneyText(income);$('expenseSummary').textContent=moneyText(expense);$('balanceSummary').textContent=balance!==undefined&&balance!==null?moneyText(balance):Number.isFinite(income)&&Number.isFinite(expense)?`${(income-expense).toLocaleString('ja-JP')}円`:'未算出';$('moneyGoal').textContent=clean(money.goal)||'未設定';
$('journeyStage').textContent=clean(journey?.stage)||clean(journey?.name)||'未設定';$('journeyScene').textContent=clean(Array.isArray(scenes)?scenes.at(-1)?.title:'')||'データなし';$('recentExperience').textContent=clean(Array.isArray(scenes)?scenes.at(-1)?.summary:'')||'データなし';$('nextTheme').textContent=clean(journey?.theme)||'未設定';const idea=read(KEYS.idea,read(KEYS.legacyIdea,{}));$('ideaMemo').value=clean(idea.text||idea.memo,1000)}
const titles={home:'MY WAY',money:'MY MONEY',journey:'MY JOURNEY',idea:'MY IDEA',archive:'MY WAY'};
function showPage(name){document.querySelectorAll('[data-page-panel]').forEach(panel=>{const active=panel.dataset.pagePanel===name;panel.hidden=!active;panel.classList.toggle('active',active)});document.querySelectorAll('.bottom-nav [data-page]').forEach(item=>item.classList.toggle('active',item.dataset.page===name));$('brandTitle').textContent=titles[name]||'MY WAY';document.body.dataset.domain=name;window.scrollTo(0,0)}
async function openYos(prompt){try{await navigator.clipboard.writeText(prompt)}catch{}const url=sharedUrl();$('menuDialog').close();if(url.startsWith('https://chatgpt.com/')){location.href=url;return}$('appStatus').textContent='現在のYOSチャットURLを設定してください。';$('yosUrl').value=url;$('settingsDialog').showModal()}
document.querySelectorAll('[data-page]').forEach(item=>item.addEventListener('click',()=>showPage(item.dataset.page)));document.querySelectorAll('[data-prompt]').forEach(item=>item.addEventListener('click',()=>openYos(item.dataset.prompt)));
$('openMenu').addEventListener('click',()=>$('menuDialog').showModal());$('menuDialog').querySelector('.close').addEventListener('click',()=>$('menuDialog').close());$('openSettings').addEventListener('click',()=>{$('menuDialog').close();$('yosUrl').value=sharedUrl();$('settingsDialog').showModal()});$('saveUrl').addEventListener('click',()=>{settings.yosUrl=clean($('yosUrl').value,500);write(KEYS.home,settings)});
$('focusIdea').addEventListener('click',()=>$('ideaMemo').focus());$('saveIdea').addEventListener('click',()=>{const text=clean($('ideaMemo').value,1000);$('appStatus').textContent=write(KEYS.idea,{text,memo:text,savedAt:new Date().toISOString()})?'アイデアメモを保存しました。':'保存できませんでした。'});
render();const initial=location.hash.slice(1);if(['money','journey','idea','archive'].includes(initial))showPage(initial);if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./service-worker.js').catch(()=>{}));
})();
