"use strict";
(()=>{const S=["日常世界","冒険への誘い","ためらい","メンターとの出会い","最初の境界線","試練・仲間・敵","最も深い場所へ","最大の試練","報酬","帰路","復活","宝を持って帰還"],K={j:"hj-domain-journeys-v1",s:"hj-daily-scenes-v1",w:"hj-weekly-stories-v1"},$=id=>document.getElementById(id),read=(k,d)=>{try{return JSON.parse(localStorage.getItem(k)||"null")??d}catch{return d}},write=(k,v)=>{try{localStorage.setItem(k,JSON.stringify(v));return true}catch{return false}},clean=(v,n)=>typeof v==="string"?v.trim().slice(0,n):"",status=m=>{$("appStatus")&&($("appStatus").textContent=m)},js=()=>{const v=read(K.j,[]);return Array.isArray(v)?v:[]},ss=()=>{const v=read(K.s,[]);return Array.isArray(v)?v:[]},ws=()=>{const v=read(K.w,[]);return Array.isArray(v)?v:[]};
function local(v){const d=new Date(v||Date.now()),o=d.getTimezoneOffset()*6e4;return new Date(d-o).toISOString().slice(0,16)}
function week(){const n=new Date();n.setHours(0,0,0,0);const s=new Date(n);s.setDate(n.getDate()-(n.getDay()+6)%7);const e=new Date(s);e.setDate(s.getDate()+7);return ss().filter(v=>{const t=new Date(v.occurredAt).getTime();return t>=s.getTime()&&t<e.getTime()}).sort((a,b)=>new Date(b.occurredAt)-new Date(a.occurredAt))}
function domains(sel,v){sel.innerHTML="";js().forEach(j=>{const o=document.createElement("option");o.value=j.id;o.textContent=`${j.icon||"🧭"} ${j.name}`;o.selected=j.id===v;sel.appendChild(o)})}
function stages(sel,v){sel.innerHTML="";S.forEach(s=>{const o=document.createElement("option");o.value=s;o.textContent=s;o.selected=s===v;sel.appendChild(o)})}
function open(id){const v=ss().find(x=>x.id===id);if(!v)return;$("editSceneId").value=v.id;$("editSceneAt").value=local(v.occurredAt);domains($("editSceneDomain"),v.domainId);stages($("editSceneStage"),v.stage);$("editSceneFact").value=v.fact||"";$("editSceneChoice").value=v.choice||"";$("editSceneResult").value=v.result||"";$("editSceneReflection").value=v.reflection||"";$("sceneEditDialog").showModal()}
function save(e){e.preventDefault();const a=ss(),i=a.findIndex(v=>v.id===$("editSceneId").value),fact=clean($("editSceneFact").value,600);if(i<0||!fact){status("実際に起きたことは空欄にできません。");return}const d=new Date($("editSceneAt").value||Date.now());a[i]={...a[i],occurredAt:Number.isNaN(d.getTime())?a[i].occurredAt:d.toISOString(),domainId:$("editSceneDomain").value,stage:S.includes($("editSceneStage").value)?$("editSceneStage").value:S[0],fact,choice:clean($("editSceneChoice").value,400),result:clean($("editSceneResult").value,400),reflection:clean($("editSceneReflection").value,400),updatedAt:new Date().toISOString()};write(K.s,a);$("sceneEditDialog").close();status("シーンの事実を修正しました。");setTimeout(()=>location.reload(),180)}
function decorateScenes(){const cards=[...document.querySelectorAll("#sceneHistory .scene-item")],items=week();cards.forEach((c,i)=>{const v=items[i];if(!v||c.querySelector(".scene-edit"))return;const b=document.createElement("button");b.className="scene-edit";b.type="button";b.textContent="編集";b.onclick=e=>{e.stopPropagation();open(v.id)};const x=c.querySelector(".scene-delete");x?c.insertBefore(b,x):c.appendChild(b)})}
function decorateStories(){const cards=[...document.querySelectorAll("#storyHistory article")],items=ws().slice(0,10);cards.forEach((c,i)=>{const v=items[i];if(!v||c.querySelector(".story-delete"))return;const b=document.createElement("button");b.className="story-delete";b.type="button";b.textContent="削除";b.onclick=e=>{e.stopPropagation();if(!confirm("この作品を本棚から削除しますか？"))return;write(K.w,ws().filter(x=>x.id!==v.id));status("作品を本棚から削除しました。");setTimeout(()=>location.reload(),180)};c.appendChild(b)})}
new MutationObserver(decorateScenes).observe($("sceneHistory"),{childList:true});new MutationObserver(decorateStories).observe($("storyHistory"),{childList:true});$("sceneEditForm")?.addEventListener("submit",save);$("cancelSceneEdit")?.addEventListener("click",()=>$("sceneEditDialog").close());$("editSceneDomain")?.addEventListener("change",()=>{const j=js().find(v=>v.id===$("editSceneDomain").value);stages($("editSceneStage"),j?.stage||S[0])});decorateScenes();decorateStories()})();