"use strict";
(()=>{const S=["日常世界","冒険への誘い","ためらい","メンターとの出会い","最初の境界線","試練・仲間・敵","最も深い場所へ","最大の試練","報酬","帰路","復活","宝を持って帰還"],K={j:"hj-domain-journeys-v1",p:"hj-user-profile-v1",s:"hj-daily-scenes-v1",h:"hj-stage-history-v1",x:"hj-stage-snapshot-v1",f:"hj-user-preferences-v1",home:"yos-home-settings-v2",legacy:"yos-home-settings-v1",taxi:"yos-taxi-settings-v2"},$=id=>document.getElementById(id),read=(k,d)=>{try{return JSON.parse(localStorage.getItem(k)||"null")??d}catch{return d}},write=(k,v)=>{try{localStorage.setItem(k,JSON.stringify(v));return true}catch{return false}},clean=(v,n=160)=>typeof v==="string"?v.trim().slice(0,n):"",uid=()=>crypto.randomUUID?.()||`${Date.now()}-${Math.random()}`,js=()=>{const v=read(K.j,[]);return Array.isArray(v)?v:[]},hs=()=>{const v=read(K.h,[]);return Array.isArray(v)?v:[]},snap=(a=js())=>Object.fromEntries(a.map(j=>[j.id,{name:clean(j.name,24),stage:S.includes(j.stage)?j.stage:S[0],cycle:Math.max(1,Math.min(99,+j.cycle||1)),theme:clean(j.theme)}])),status=m=>{$("appStatus")&&($("appStatus").textContent=m)},fmt=v=>{const d=new Date(v);return Number.isNaN(d.getTime())?"日時不明":new Intl.DateTimeFormat("ja-JP",{month:"numeric",day:"numeric",hour:"2-digit",minute:"2-digit",hour12:false,timeZone:"Asia/Tokyo"}).format(d)};
function render(){const b=$("spiralHistory");if(!b)return;const a=hs().slice(0,16);b.innerHTML="";a.forEach((e,i)=>{const n=Math.max(1,S.indexOf(e.toStage)+1),m=e.type==="start"?`旅を開始：${n}/12「${e.toStage}」・${e.toCycle}周目`:e.type==="theme"?`テーマを更新：${e.theme}`:`${Math.max(1,S.indexOf(e.fromStage)+1)}/12「${e.fromStage}」から ${n}/12「${e.toStage}」へ`,el=document.createElement("article");el.className="spiral-event";el.innerHTML=`<span class="spiral-node">${i+1}</span><div><strong>${e.journeyName||"旅"}</strong><p>${m}</p><small>${fmt(e.changedAt)}${e.theme&&e.type!=="theme"?` · ${e.theme}`:""}</small></div>`;b.appendChild(el)});$("emptySpiralHistory").hidden=!!a.length;$("historySummary").textContent=`${hs().length}件`}
function sync(){const c=snap(),p=read(K.x,{}),a=hs(),now=new Date().toISOString();Object.entries(c).forEach(([id,n])=>{const o=p[id];if(!o)a.unshift({id:uid(),journeyId:id,journeyName:n.name,type:"start",fromStage:"",fromCycle:0,toStage:n.stage,toCycle:n.cycle,theme:n.theme,changedAt:now});else if(o.stage!==n.stage||+o.cycle!==+n.cycle)a.unshift({id:uid(),journeyId:id,journeyName:n.name,type:"move",fromStage:o.stage,fromCycle:+o.cycle||1,toStage:n.stage,toCycle:n.cycle,theme:n.theme,changedAt:now});else if(o.theme!==n.theme&&n.theme)a.unshift({id:uid(),journeyId:id,journeyName:n.name,type:"theme",fromStage:n.stage,fromCycle:n.cycle,toStage:n.stage,toCycle:n.cycle,theme:n.theme,changedAt:now})});write(K.h,a.slice(0,300));write(K.x,c);render()}
function prefs(){const v=read(K.f,{});return v&&typeof v==="object"?v:{}}
function fill(){const p=prefs();$("profileFormat")&&($("profileFormat").value=["manga","newspaper","novel","picturebook"].includes(p.storyFormat)?p.storyFormat:"manga");$("profileTone")&&($("profileTone").value=["balanced","gentle","direct"].includes(p.mentorTone)?p.mentorTone:"balanced")}
function savePrefs(){write(K.f,{storyFormat:$("profileFormat")?.value||"manga",mentorTone:$("profileTone")?.value||"balanced",updatedAt:new Date().toISOString()})}
function week(){const n=new Date();n.setHours(0,0,0,0);const s=new Date(n);s.setDate(n.getDate()-(n.getDay()+6)%7);const e=new Date(s);e.setDate(s.getDate()+7);const a=read(K.s,[]);return(Array.isArray(a)?a:[]).filter(v=>{const t=new Date(v.occurredAt).getTime();return t>=s.getTime()&&t<e.getTime()}).sort((a,b)=>new Date(a.occurredAt)-new Date(b.occurredAt))}
async function copy(t){try{await navigator.clipboard.writeText(t);return true}catch{const a=document.createElement("textarea");a.value=t;a.style.position="fixed";a.style.opacity="0";document.body.appendChild(a);a.select();const ok=document.execCommand("copy");a.remove();return ok}}
function url(){const a=read(K.home,{}),b=read(K.legacy,{}),c=read(K.taxi,{});return a.yosUrl||b.yosUrl||c.yosUrl||""}
async function consult(ev){ev.preventDefault();ev.stopImmediatePropagation();const p=read(K.p,{}),q=prefs(),tone=q.mentorTone==="gentle"?"優しく寄り添いながら、曖昧にせず伝える":q.mentorTone==="direct"?"結論を先に、率直かつ短く伝える":"率直さと優しさのバランスを取る",jl=js().map(j=>`- ${j.name}：${Math.max(1,S.indexOf(j.stage)+1)}/12「${j.stage}」・${j.cycle||1}周目${j.theme?`・テーマ「${j.theme}」`:""}`),sl=week().slice(-8).map(v=>{const d=js().find(j=>j.id===v.domainId);return`- ${fmt(v.occurredAt)}［${d?.name||"未設定"}／${v.stage}］${v.fact}`}),hl=hs().slice(0,5).map(e=>`- ${e.journeyName}：${e.fromStage||"開始"} → ${e.toStage}（${e.toCycle||1}周目）`),text=["【Hero’s Journey｜現在地相談】",`主人公：${p.name||"主人公"}`,`希望する話し方：${tone}`,"","領域ごとの現在地",...jl,"","今週の事実",...(sl.length?sl:["- 未記録"]),"","直近のステージ変化",...(hl.length?hl:["- 未記録"]),"","複数の旅を一つの順位にまとめず、相互関係を見てください。","安全と本人の価値観を優先し、今できる小さな一歩を一つだけ提案してください。","推測は推測と明記し、ステージ判断は本人に確認してください。"].join("\n"),ok=await copy(text),u=url();if(u.startsWith("https://chatgpt.com/")){status(ok?"現在地と直近の事実をコピーしてYOSを開きます。":"YOSを開きます。");location.href=u}else status(ok?"現在地と直近の事実をコピーしました。YOSホームでチャットURLを設定してください。":"相談文をコピーできませんでした。")}
$("consultYos")?.addEventListener("click",consult,true);$("editProfile")?.addEventListener("click",()=>setTimeout(fill,20));$("onboardingForm")?.addEventListener("submit",savePrefs,true);window.addEventListener("hj:data-changed",()=>setTimeout(sync,30));document.addEventListener("click",e=>{if(e.target?.dataset?.role==="save"||e.target?.id==="addDomain")setTimeout(sync,80)},true);fill();const preferred=prefs().storyFormat,btn=document.querySelector(`[data-format="${preferred}"]`);btn?.click();sync()})();